import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'id' | 'en' | 'ja';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  id: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.meetingRooms': 'Ruangan Rapat',
    'nav.aiAssistant': 'Asisten AI',
    'nav.reservations': 'Reservasi',
    'nav.history': 'Riwayat',
    'nav.profile': 'Profil',
    'nav.settings': 'Pengaturan',
    'nav.helpCenter': 'Pusat Bantuan',
    
    // Settings
    'settings.title': 'Pengaturan',
    'settings.appearance': 'Tampilan',
    'settings.darkMode': 'Mode Gelap',
    'settings.darkModeDesc': 'Aktifkan tema gelap',
    'settings.language': 'Bahasa',
    'settings.privacySecurity': 'Privasi & Keamanan',
    'settings.changePassword': 'Ubah Password',
    'settings.twoFactorAuth': 'Verifikasi 2FA',
    'settings.saveSettings': 'Simpan Pengaturan',
    
    // Language options
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English',
    'language.japanese': '日本語',
    
    // Common
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.loading': 'Memuat...',
    'common.error': 'Terjadi kesalahan',
    'common.success': 'Berhasil',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Selamat datang',
    'dashboard.upcomingMeetings': 'Rapat Mendatang',
    'dashboard.quickActions': 'Aksi Cepat',
    'dashboard.heroTitle': 'Biarkan AI Membantu Anda Memesan Ruang Rapat yang Sempurna!',
    'dashboard.heroSubtitle': 'Temukan dan pesan ruang rapat ideal secara instan dengan bantuan Asisten AI cerdas kami. Proses pemesanan jadi lebih cepat, efisien, dan sesuai kebutuhan Anda.',
    'dashboard.upcomingReservations': 'Reservasi Terdekat',
    'dashboard.bookingHistory': 'Histori Pemesanan',
    'dashboard.featuredFeatures': 'Fitur Unggulan',
    'dashboard.smartRecommendations': 'Rekomendasi Cerdas',
    'dashboard.smartRecommendationsDesc': 'AI kami akan merekomendasikan ruang terbaik berdasarkan kebutuhan Anda, jumlah peserta, dan preferensi fasilitas.',
    'dashboard.automaticScheduling': 'Penjadwalan Otomatis',
    'dashboard.automaticSchedulingDesc': 'Secara otomatis menemukan slot waktu terbaik yang sesuai untuk semua peserta rapat tanpa konflik jadwal.',
    'dashboard.naturalLanguage': 'Bahasa Alami',
    'dashboard.naturalLanguageDesc': 'Berinteraksi dengan Asisten AI kami menggunakan bahasa manusia untuk pengalaman pemesanan yang lebih intuitif.',
    'dashboard.noReservations': 'Anda belum memiliki reservasi.',
    'dashboard.noReservationsDesc': 'Coba buat reservasi melalui AI Assistant atau form manual.',
    'dashboard.viewAllReservations': 'Lihat Semua Reservasi',
    'dashboard.viewHistory': 'Lihat Histori',
    'dashboard.viewRispat': 'View Rispat',
    'dashboard.historyDesc': 'Ringkasan histori terbaru Anda (tersimpan lokal meski data database telah dihapus).',
    
    // Cancel Requests
    'dashboard.cancelRequests': 'Permintaan Pembatalan',
    'dashboard.cancelRequestsDesc': 'Kelola semua permintaan pembatalan reservasi',
    'dashboard.manageRequests': 'Kelola Permintaan',
    'dashboard.cancelRequestsInstruction': 'Klik tombol di atas untuk melihat dan mengelola semua permintaan pembatalan',
    
    // History Page
    'history.title': 'Histori Pemesanan',
    'history.subtitle': 'Riwayat pemesanan ruang rapat Anda',
    'history.selectDate': 'Pilih Tanggal',
    'history.bookingStatus': 'Status Pemesanan',
    'history.statusDescription': 'Menampilkan pemesanan (dibatalkan & selesai) pada tanggal yang dipilih',
    'history.noHistory': 'Tidak ada histori',
    'history.noHistoryDesc': 'Belum ada pemesanan pada tanggal yang dipilih',
    'history.cancelReason': 'Alasan Pembatalan',
    'history.expired': 'Expired',
    
    // Rispat Page
    'rispat.title': 'View Rispat',
    'rispat.subtitle': 'Lihat dan kelola risalah rapat yang sudah selesai',
    'rispat.selectDate': 'Pilih Tanggal',
    'rispat.meetingMinutes': 'Risalah Rapat',
    'rispat.description': 'Menampilkan pemesanan yang sudah selesai untuk melihat risalah rapat',
    'rispat.noMinutes': 'Tidak ada risalah rapat',
    'rispat.noMinutesDesc': 'Belum ada pemesanan yang sudah selesai pada tanggal ini',
    'rispat.completed': 'Selesai',
    'rispat.modalTitle': 'Risalah Rapat',
    
    // Meeting Rooms Page
    'meetingRooms.searchPlaceholder': 'Cari ruangan, lokasi, atau fasilitas...',
    'meetingRooms.allCapacities': 'Semua Kapasitas',
    'meetingRooms.allStatus': 'Semua Status',
    'meetingRooms.available': 'Tersedia',
    'meetingRooms.maintenance': 'Maintenance',
    'meetingRooms.reset': 'Reset',
    'meetingRooms.showingResults': 'Menampilkan {filtered} dari {total} ruangan',
    'meetingRooms.noSearchResults': 'Tidak ada ruangan yang sesuai dengan kriteria pencarian',
    'meetingRooms.roomsUsed': 'Rooms Used',
    'meetingRooms.capacity2': '2+ Orang',
    'meetingRooms.capacity4': '4+ Orang',
    'meetingRooms.capacity6': '6+ Orang',
    'meetingRooms.capacity8': '8+ Orang',
    'meetingRooms.capacity10': '10+ Orang',
    'meetingRooms.capacity15': '15+ Orang',
    'meetingRooms.capacity20': '20+ Orang',
    
    // Room Detail Page
    'roomDetail.roomInfo': 'Informasi Ruangan',
    'roomDetail.capacity': 'Kapasitas',
    'roomDetail.floor': 'Lantai',
    'roomDetail.address': 'Alamat',
    'roomDetail.facilities': 'Fasilitas',
    'roomDetail.status': 'Status',
    'roomDetail.available': 'Tersedia',
    'roomDetail.ongoing': 'Sedang Berlangsung',
    'roomDetail.upcoming': 'Akan Datang',
    'roomDetail.maintenance': 'Maintenance',
    'roomDetail.bookingSchedule': 'Jadwal Booking',
    'roomDetail.selectDate': 'Pilih Tanggal',
    'roomDetail.quickOptions': 'Pilihan Cepat',
    'roomDetail.today': 'Hari Ini',
    'roomDetail.tomorrow': 'Besok',
    'roomDetail.nextWeek': 'Minggu Depan',
    'roomDetail.nextMonth': 'Bulan Depan',
    'roomDetail.datesWithBookings': 'Tanggal dengan Booking',
    'roomDetail.noBookings': 'Tidak ada booking untuk {date}',
    'roomDetail.roomAvailableAllDay': 'Ruangan tersedia sepanjang hari',
    'roomDetail.bookRoom': 'Pesan Ruangan',
    'roomDetail.unavailable': 'Unavailable',
    'roomDetail.availableTimeSlots': 'Slot Waktu Tersedia - {date}',
    'roomDetail.past': 'PAST',
    'roomDetail.booked': 'Sudah Dipesan',
    'roomDetail.pastTime': 'Waktu Lalu',
    'roomDetail.tips': 'Tips:',
    'roomDetail.tip1': 'Klik slot hijau untuk memesan ruangan pada waktu tersebut',
    'roomDetail.tip2': 'Slot merah tidak bisa diklik karena sudah dipesan',
    'roomDetail.tip3': 'Hover pada slot merah untuk melihat detail pemesanan yang sudah ada',
    'roomDetail.tip4': 'Slot abu-abu menunjukkan waktu yang sudah lewat',
    'roomDetail.edit': 'Edit',
    'roomDetail.activate': 'Aktifkan',
    'roomDetail.deactivate': 'Nonaktifkan',
    'roomDetail.delete': 'Hapus',
    'roomDetail.cancel': 'Batal',
    'roomDetail.processing': 'Memproses...',
    'roomDetail.cannotDeactivate': 'Tidak Dapat Dinonaktifkan',
    'roomDetail.confirmActivate': 'Ya, Aktifkan',
    'roomDetail.confirmDeactivate': 'Ya, Nonaktifkan',
    'roomDetail.people': 'orang',
    'roomDetail.bookingScheduleTitle': 'Jadwal Booking - {date}',
    'roomDetail.totalBookings': 'Total {count} pemesanan untuk hari ini',
    'roomDetail.booked': 'BOOKED',
    'roomDetail.date': 'Tanggal',
    'roomDetail.time': 'Waktu',
    'roomDetail.pic': 'PIC',
    'roomDetail.participants': 'Peserta',
    'roomDetail.type': 'Jenis',
    'roomDetail.facilities': 'Fasilitas',
    'roomDetail.duration': 'Durasi',
    'roomDetail.hours': 'jam',
    'roomDetail.minutes': 'menit',
    'roomDetail.slot': 'Slot',
    'roomDetail.scrollHint': '← Geser untuk melihat booking lainnya →',
    'roomDetail.availableTimeSlots': 'Slot Waktu Tersedia - {date}',
    'roomDetail.notAvailable': 'Tidak tersedia',
    'roomDetail.past': 'PAST',
    'roomDetail.available': 'Tersedia',
    'roomDetail.booked': 'Sudah Dipesan',
    'roomDetail.pastTime': 'Waktu Lalu',
    'roomDetail.tips': 'Tips:',
    'roomDetail.tip1': 'Klik slot hijau untuk memesan ruangan pada waktu tersebut',
    'roomDetail.tip2': 'Slot merah tidak bisa diklik karena sudah dipesan',
    'roomDetail.tip3': 'Hover pada slot merah untuk melihat detail pemesanan yang sudah ada',
    'roomDetail.tip4': 'Slot abu-abu menunjukkan waktu yang sudah lewat',
    'roomDetail.tip5': 'Gunakan navigasi tanggal untuk melihat booking di hari lain',
    'roomDetail.confirmBooking': 'Konfirmasi Pemesanan',
    'roomDetail.bookingConfirmation': 'Anda akan memesan ruangan untuk waktu yang dipilih',
    'roomDetail.room': 'Ruangan',
    'roomDetail.date': 'Tanggal',
    'roomDetail.time': 'Waktu',
    'roomDetail.noFacilities': 'Tidak ada',
    'roomDetail.meeting': 'Meeting',
    'roomDetail.internal': 'internal',
    
    // Cancel Requests Page
    'cancelRequests.title': 'Permintaan Pembatalan',
    'cancelRequests.subtitle': 'Kelola semua permintaan pembatalan reservasi',
    'cancelRequests.loading': 'Memuat permintaan pembatalan...',
    'cancelRequests.all': 'Semua',
    'cancelRequests.pending': 'Menunggu',
    'cancelRequests.approved': 'Disetujui',
    'cancelRequests.rejected': 'Ditolak',
    'cancelRequests.noRequests': 'Tidak Ada Permintaan',
    'cancelRequests.noRequestsDesc': 'Belum ada permintaan pembatalan reservasi.',
    'cancelRequests.noRequestsFilter': 'Tidak ada permintaan dengan status "{status}".',
    'cancelRequests.requestId': 'Permintaan Pembatalan #{id}',
    'cancelRequests.from': 'Dari',
    'cancelRequests.to': 'Untuk',
    'cancelRequests.reservation': 'Reservasi',
    'cancelRequests.aiBooking': 'AI Booking',
    'cancelRequests.formBooking': 'Form Booking',
    'cancelRequests.cancellationReason': 'Alasan Pembatalan',
    'cancelRequests.responseMessage': 'Pesan Balasan',
    'cancelRequests.replyMessage': 'Pesan Balasan (Opsional)',
    'cancelRequests.replyPlaceholder': 'Berikan pesan balasan untuk peminta...',
    'cancelRequests.characters': 'karakter',
    'cancelRequests.processing': 'Memproses...',
    'cancelRequests.reject': 'Tolak',
    'cancelRequests.approve': 'Setujui',
    'cancelRequests.requestApproved': '✅ Permintaan Anda telah disetujui',
    'cancelRequests.requestRejected': '❌ Permintaan Anda telah ditolak',
    'cancelRequests.message': 'Pesan',
    'cancelRequests.waitingResponse': 'Menunggu Respon',
    'cancelRequests.approved': 'Disetujui',
    'cancelRequests.rejected': 'Ditolak',
    
    // Notification Bell
    'notification.title': 'Notifikasi',
    'notification.pendingRequests': '{count} permintaan pembatalan menunggu respons',
    'notification.noNewNotifications': 'Tidak ada notifikasi baru',
    'notification.noCancellationRequests': 'Tidak ada permintaan pembatalan',
    'notification.cancellationRequestFrom': 'Permintaan pembatalan dari {requester}',
    'notification.viewAllRequests': 'Lihat Semua Permintaan →',
    
    // Booking Form Page
    'bookingForm.title': 'Formulir Pemesanan',
    'bookingForm.subtitle': 'Isi formulir untuk memesan ruangan meeting',
    'bookingForm.selectRoom': 'Pilih Ruangan *',
    'bookingForm.loadingRooms': 'Memuat ruangan...',
    'bookingForm.selectRoomPlaceholder': 'Pilih ruangan meeting',
    'bookingForm.people': 'orang',
    'bookingForm.inactive': '- ❌ Nonaktif',
    'bookingForm.topic': 'Topik / Nama Rapat *',
    'bookingForm.topicPlaceholder': 'Masukkan topik atau nama rapat',
    'bookingForm.pic': 'PIC (Person in Charge) *',
    'bookingForm.picPlaceholder': 'Masukkan nama PIC',
    'bookingForm.participants': 'Jumlah Peserta *',
    'bookingForm.participantsPlaceholder': 'Jumlah peserta',
    'bookingForm.meetingDate': 'Tanggal Rapat *',
    'bookingForm.meetingTime': 'Waktu Rapat *',
    'bookingForm.startTime': 'Mulai:',
    'bookingForm.endTime': 'Berakhir:',
    'bookingForm.duration': 'Durasi:',
    'bookingForm.invalidTime': 'Waktu tidak valid',
    'bookingForm.hours': 'jam',
    'bookingForm.minutes': 'menit',
    'bookingForm.meetingType': 'Jenis Rapat *',
    'bookingForm.internal': 'Internal',
    'bookingForm.external': 'Eksternal',
    'bookingForm.rispat': 'Rispat *',
    'bookingForm.no': 'Tidak',
    'bookingForm.yes': 'Ya',
    'bookingForm.rispatHint': 'Jika memilih "Ya", Anda harus mengupload rispat setelah pemesanan untuk menyelesaikan booking',
    'bookingForm.facilities': 'Fasilitas',
    'bookingForm.selectFacilities': 'Pilih fasilitas yang tersedia di {roomName}',
    'bookingForm.selectRoomFirst': 'Pilih ruangan terlebih dahulu untuk melihat fasilitas yang tersedia',
    'bookingForm.selectedFacilities': 'Fasilitas yang dipilih ({count}):',
    'bookingForm.cancel': 'Batal',
    'bookingForm.processing': 'Memproses...',
    'bookingForm.confirmBooking': 'Konfirmasi Pemesanan',
    'bookingForm.roomDetails': 'Detail Ruangan',
    'bookingForm.capacity': 'Kapasitas',
    'bookingForm.floor': 'Lantai',
    'bookingForm.address': 'Alamat',
    'bookingForm.availableFacilities': 'Fasilitas Tersedia',
    
    // Reservation Detail Page
    'reservationDetail.title': 'Detail Reservasi',
    'reservationDetail.subtitle': 'Informasi lengkap reservasi meeting room',
    'reservationDetail.meeting': 'Rapat',
    'reservationDetail.date': 'Tanggal',
    'reservationDetail.startTime': 'Waktu Mulai',
    'reservationDetail.endTime': 'Waktu Berakhir',
    'reservationDetail.pic': 'PIC',
    'reservationDetail.participants': 'Peserta',
    'reservationDetail.people': 'orang',
    'reservationDetail.meetingType': 'Jenis Rapat',
    'reservationDetail.facilities': 'Fasilitas',
    'reservationDetail.noSpecialFacilities': 'Tidak ada fasilitas khusus',
    'reservationDetail.meetingMinutes': 'Risalah Rapat',
    'reservationDetail.noMinutesFile': 'Belum ada file risalah',
    'reservationDetail.filesAvailable': '{count} file tersedia',
    'reservationDetail.meetingOngoing': 'Rapat sedang berlangsung - Upload tersedia',
    'reservationDetail.meetingNotStarted': 'Rapat belum dimulai - Upload tidak tersedia',
    'reservationDetail.meetingFinished': 'Rapat sudah selesai - Upload tidak tersedia',
    'reservationDetail.upload': 'Upload',
    'reservationDetail.view': 'Lihat',
    'reservationDetail.uploadMinutes': 'Upload risalah rapat',
    'reservationDetail.uploadOnlyDuringMeeting': 'Upload hanya bisa dilakukan saat rapat sedang berlangsung',
    'reservationDetail.summary': 'Ringkasan',
    'reservationDetail.summarySubtitle': 'Informasi singkat reservasi',
    'reservationDetail.meetingRoom': 'Ruangan Meeting',
    'reservationDetail.until': 'Sampai',
    'reservationDetail.meetingSchedule': 'Jadwal Meeting',
    'reservationDetail.participantCount': 'Jumlah Peserta',
    'reservationDetail.meetingInvitation': 'Undangan Rapat',
    'reservationDetail.backToReservations': 'Kembali ke Reservasi',
    'reservationDetail.uploadOnlyDuringMeetingAlert': 'Upload risalah rapat hanya bisa dilakukan saat rapat sedang berlangsung.',
    'reservationDetail.currentStatus': 'Status saat ini: {status}',
    'reservationDetail.notStarted': 'Belum dimulai',
    'reservationDetail.finished': 'Sudah selesai',
    'reservationDetail.unknown': 'Tidak diketahui',
    
    // Profile Page
    'profile.title': 'Profile',
    'profile.subtitle': 'Kelola informasi dan pengaturan akun Anda',
    'profile.active': 'Aktif',
    'profile.reservations': 'Reservasi',
    'profile.completed': 'Selesai',
    'profile.pending': 'Menunggu',
    'profile.personalInfo': 'Informasi Pribadi',
    'profile.fullName': 'Nama Lengkap',
    'profile.email': 'Email',
    'profile.role': 'Role',
    'profile.accountStatus': 'Status Akun',
    'profile.recentActivity': 'Aktivitas Terbaru',
    'profile.loadingActivities': 'Memuat aktivitas...',
    'profile.noRecentActivity': 'Belum ada aktivitas terbaru',
    'profile.startWithReservation': 'Mulai dengan membuat reservasi ruangan',
    'profile.settings': 'Pengaturan',
    'profile.settingsDesc': 'Kelola pengaturan aplikasi dan preferensi Anda',
    'profile.helpCenter': 'Pusat Bantuan',
    'profile.helpCenterDesc': 'Dapatkan bantuan dan dukungan teknis',
    'profile.roomReservation': 'Reservasi Ruangan',
    'profile.updateProfile': 'Update Profil',
    'profile.profileUpdated': 'Profil berhasil diperbarui',
    'profile.today': 'Hari ini',
    'profile.yesterday': 'Kemarin',
    'profile.daysAgo': '{days} hari lalu',
    'profile.weeksAgo': '{weeks} minggu lalu',
    'profile.weekAgo': '1 minggu lalu',
    
    // Help Center Page
    'helpCenter.title': 'Help Center',
    'helpCenter.subtitle': 'Temukan jawaban untuk pertanyaan yang sering diajukan',
    'helpCenter.faq': 'Pertanyaan yang Sering Diajukan',
    'helpCenter.quickActions': 'Aksi Cepat',
    'helpCenter.contactUs': 'Hubungi Kami',
    'helpCenter.aiAssistant': 'AI Assistant',
    'helpCenter.aiAssistantDesc': 'Dapatkan bantuan instan dengan AI Assistant kami yang siap membantu 24/7',
    'helpCenter.chatWithAI': 'Chat dengan AI',
    'helpCenter.viewMeetingRooms': 'Lihat Ruangan Meeting',
    'helpCenter.viewMyBookings': 'Lihat Booking Saya',
    'helpCenter.phone': 'Telepon',
    'helpCenter.email': 'Email',
    'helpCenter.operatingHours': 'Jam operasional: Senin - Jumat, 08:00 - 17:00 WIB',
    'helpCenter.faq1Question': 'Bagaimana cara booking ruangan meeting?',
    'helpCenter.faq1Answer': 'Pilih menu \'Meeting Rooms\', pilih ruangan yang tersedia, lalu klik \'Book Now\' dan isi form booking.',
    'helpCenter.faq2Question': 'Apakah bisa membatalkan booking?',
    'helpCenter.faq2Answer': 'Ya, Anda bisa membatalkan booking melalui menu \'Reservations\' dan klik tombol \'Cancel\' pada booking yang ingin dibatalkan.',
    'helpCenter.faq3Question': 'Berapa lama durasi maksimal booking?',
    'helpCenter.faq3Answer': 'Durasi maksimal booking adalah 8 jam per hari untuk setiap ruangan.',
    'helpCenter.faq4Question': 'Apakah ada biaya untuk booking ruangan?',
    'helpCenter.faq4Answer': 'Booking ruangan meeting adalah gratis untuk karyawan perusahaan.',
    'helpCenter.faq5Question': 'Bagaimana jika ruangan yang diinginkan sudah dibooking?',
    'helpCenter.faq5Answer': 'Anda bisa melihat jadwal booking di halaman \'Meeting Rooms\' dan memilih waktu yang tersedia.',
    
    // Navigation
    'nav.logout': 'Logout',
    
    // Settings Page
    'settings.subtitle': 'Kelola pengaturan aplikasi dan preferensi Anda',
    'settings.languageDesc': 'Pilih bahasa yang Anda inginkan',
    'settings.changePasswordDesc': 'Ubah kata sandi Anda',
    'settings.twoFactorAuthDesc': 'Tingkatkan keamanan akun',
    'settings.notifications': 'Notifikasi',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.accountManagement': 'Manajemen Akun',
    'settings.exportData': 'Export Data',
    'settings.exportDataDesc': 'Download data Anda',
    'settings.deleteAccount': 'Hapus Akun',
    'settings.deleteAccountDesc': 'Hapus akun secara permanen',
    'settings.settingsSaved': 'Pengaturan berhasil disimpan!',
    'settings.saveError': 'Gagal menyimpan pengaturan. Silakan coba lagi.',
    'settings.saving': 'Menyimpan...',
    'settings.unsavedChanges': 'Anda memiliki perubahan yang belum disimpan',
    'settings.currentPassword': 'Password Saat Ini',
    'settings.newPassword': 'Password Baru',
    'settings.confirmPassword': 'Konfirmasi Password',
    'settings.enterCurrentPassword': 'Masukkan password saat ini',
    'settings.enterNewPassword': 'Masukkan password baru',
    'settings.confirmNewPassword': 'Konfirmasi password baru',
    'settings.passwordRequired': 'Semua field password harus diisi',
    'settings.passwordMismatch': 'Password baru dan konfirmasi tidak cocok',
    'settings.passwordTooShort': 'Password minimal 6 karakter',
    'settings.passwordChanged': 'Password berhasil diubah! Anda akan dialihkan ke halaman login.',
    'settings.passwordChangeError': 'Gagal mengubah password. Silakan coba lagi.',
    'settings.cancel': 'Batal',
    'settings.deleteWarning': 'Peringatan!',
    'settings.deleteWarningDesc': 'Tindakan ini tidak dapat dibatalkan. Semua data Anda akan dihapus secara permanen.',
    'settings.typeDeleteToConfirm': 'Ketik "delete" untuk konfirmasi',
    'settings.deleteConfirmationRequired': 'Anda harus mengetik "delete" untuk konfirmasi',
    'settings.accountDeleted': 'Akun berhasil dihapus. Anda akan dialihkan ke halaman login.',
    'settings.deleteAccountError': 'Gagal menghapus akun. Silakan coba lagi.',
    'settings.deleting': 'Menghapus...',
    
    // AI Assistant
    'ai.greeting': 'Halo! 👋 Saya adalah asisten AI Spacio yang siap membantu Anda memesan ruang rapat dengan mudah! 🎯',
    'ai.bookRoom': 'Pesan Ruangan',
    'ai.help': 'Bantuan',
    'ai.clickMessage': 'Halo! Saya adalah Spacio Aplikasi Ruang Meeting AI',
    'ai.chatButton': 'Mari Mengobrol dengan AI!',
    
    // Booking
    'booking.title': 'Pemesanan Ruangan',
    'booking.confirm': 'Konfirmasi Pemesanan',
    'booking.cancel': 'Batalkan Pemesanan',
    'booking.success': 'Pemesanan berhasil!',
    
    // Profile
    'profile.title': 'Profil',
    'profile.settings': 'Pengaturan',
    'profile.settingsDesc': 'Ubah preferensi akun',
    'profile.helpCenter': 'Pusat Bantuan',
    'profile.helpCenterDesc': 'Dapatkan bantuan dan dukungan',
    
    // Meeting Rooms
    'meetingRooms.title': 'Meeting Rooms',
    'meetingRooms.subtitle': 'Discover and book the perfect meeting space for your needs',
    'meetingRooms.addRoom': 'Add Room',
    'meetingRooms.totalRooms': 'Total Ruangan',
    'meetingRooms.availableRooms': 'Ruangan Tersedia',
    'meetingRooms.totalCapacity': 'Total Kapasitas',
    'meetingRooms.loading': 'Memuat data ruangan...',
    'meetingRooms.error': 'Gagal Memuat Data',
    'meetingRooms.retry': 'Coba Lagi',
    'meetingRooms.noRooms': 'Belum Ada Ruangan',
    'meetingRooms.noRoomsDesc': 'Belum ada ruangan meeting yang tersedia. Tambahkan ruangan pertama untuk memulai.',
    'meetingRooms.addFirstRoom': '➕ Tambah Ruangan Pertama',
    'meetingRooms.available': 'Tersedia',
    'meetingRooms.ongoing': 'Sedang Berlangsung',
    'meetingRooms.upcoming': 'Akan Datang',
    'meetingRooms.occupied': 'Sedang Digunakan',
    'meetingRooms.full': 'Penuh',
    'meetingRooms.left': 'Tersisa',
    'meetingRooms.capacity': 'Kapasitas',
    'meetingRooms.address': 'Alamat',
    'meetingRooms.facilities': 'Fasilitas',
    'meetingRooms.book': 'Pesan',
    'meetingRooms.people': 'orang',
    
    // Reservations
    'reservations.title': 'Reservasi Saya',
    'reservations.subtitle': 'Kelola dan pantau semua reservasi meeting room Anda',
    'reservations.totalReservations': 'Total Reservasi',
    'reservations.activeReservations': 'Reservasi Aktif',
    'reservations.roomsUsed': 'Ruangan Digunakan',
    'reservations.searchPlaceholder': 'Cari berdasarkan topik atau ruangan...',
    'reservations.sortNewest': 'Terbaru',
    'reservations.sortOldest': 'Terlama',
    'reservations.noReservations': 'Tidak Ada Reservasi',
    'reservations.noReservationsDesc': 'Anda belum membuat pemesanan apa pun. Mulai dengan mencari ruangan yang tersedia dan buat reservasi pertama Anda.',
    'reservations.searchRooms': '🔍 Cari Ruangan',
    'reservations.active': 'Aktif',
    'reservations.date': 'Tanggal',
    'reservations.time': 'Waktu',
    'reservations.pic': 'PIC',
    'reservations.participants': 'Peserta',
    'reservations.detail': 'Detail',
    'reservations.complete': 'Selesai',
    'reservations.cancel': 'Batalkan',
    'reservations.confirmCancel': 'Apakah Anda yakin ingin membatalkan pemesanan ini? Data akan dihapus dari database.',
    'reservations.cancelSuccess': 'Pemesanan berhasil dibatalkan dan dihapus dari database!',
    'reservations.cancelError': 'Gagal membatalkan pemesanan. Silakan coba lagi.',
    'reservations.completeError': 'Gagal menyelesaikan pemesanan. Silakan coba lagi.',
    
    // Footer
    'footer.aboutUs': 'Tentang Kami',
    'footer.ourProfile': 'Profil Kami',
    'footer.contactUs': 'Kontak Kami',
    'footer.investorRelations': 'Hubungan Investor',
    'footer.annualReport': 'Laporan Tahunan',
    'footer.publications': 'Publikasi',
    'footer.news': 'Berita',
    'footer.airportInfo': 'Informasi & Profil Bandara',
    'footer.memberOf': 'Member Of',
    'footer.airportsCenter': 'InJourney Airports Center',
    'footer.airportName': 'Bandar Udara Internasional Soekarno-Hatta',
    'footer.address': 'Jl. M2, Pajang, Kec. Benda, Kota Tangerang, Banten 15126',
    'footer.companyName': 'PT Angkasa Pura Indonesia',
    'footer.copyright': 'PT Angkasa Pura Indonesia © 2024. All Rights Reserved',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.meetingRooms': 'Meeting Rooms',
    'nav.aiAssistant': 'AI Assistant',
    'nav.reservations': 'Reservations',
    'nav.history': 'History',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.helpCenter': 'Help Center',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Enable dark theme',
    'settings.language': 'Language',
    'settings.privacySecurity': 'Privacy & Security',
    'settings.changePassword': 'Change Password',
    'settings.twoFactorAuth': '2FA Verification',
    'settings.saveSettings': 'Save Settings',
    
    // Language options
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English',
    'language.japanese': '日本語',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.upcomingMeetings': 'Upcoming Meetings',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.heroTitle': 'Let AI Help You Book the Perfect Meeting Room!',
    'dashboard.heroSubtitle': 'Find and book the ideal meeting room instantly with the help of our smart AI Assistant. The booking process becomes faster, more efficient, and tailored to your needs.',
    'dashboard.upcomingReservations': 'Upcoming Reservations',
    'dashboard.bookingHistory': 'Booking History',
    'dashboard.featuredFeatures': 'Featured Features',
    'dashboard.smartRecommendations': 'Smart Recommendations',
    'dashboard.smartRecommendationsDesc': 'Our AI will recommend the best room based on your needs, number of participants, and facility preferences.',
    'dashboard.automaticScheduling': 'Automatic Scheduling',
    'dashboard.automaticSchedulingDesc': 'Automatically finds the best time slot that suits all meeting participants without schedule conflicts.',
    'dashboard.naturalLanguage': 'Natural Language',
    'dashboard.naturalLanguageDesc': 'Interact with our AI Assistant using human language for a more intuitive booking experience.',
    'dashboard.noReservations': 'You don\'t have any reservations yet.',
    'dashboard.noReservationsDesc': 'Try creating a reservation through AI Assistant or manual form.',
    'dashboard.viewAllReservations': 'View All Reservations',
    'dashboard.viewHistory': 'View History',
    'dashboard.viewRispat': 'View Rispat',
    'dashboard.historyDesc': 'Summary of your recent history (saved locally even if database data has been deleted).',
    
    // Cancel Requests
    'dashboard.cancelRequests': 'Cancellation Requests',
    'dashboard.cancelRequestsDesc': 'Manage all reservation cancellation requests',
    'dashboard.manageRequests': 'Manage Requests',
    'dashboard.cancelRequestsInstruction': 'Click the button above to view and manage all cancellation requests',
    
    // History Page
    'history.title': 'Booking History',
    'history.subtitle': 'Your meeting room booking history',
    'history.selectDate': 'Select Date',
    'history.bookingStatus': 'Booking Status',
    'history.statusDescription': 'Showing bookings (cancelled & completed) on selected date',
    'history.noHistory': 'No history',
    'history.noHistoryDesc': 'No bookings on selected date',
    'history.cancelReason': 'Cancellation Reason',
    'history.expired': 'Expired',
    
    // Rispat Page
    'rispat.title': 'View Rispat',
    'rispat.subtitle': 'View and manage completed meeting minutes',
    'rispat.selectDate': 'Select Date',
    'rispat.meetingMinutes': 'Meeting Minutes',
    'rispat.description': 'Showing completed bookings to view meeting minutes',
    'rispat.noMinutes': 'No meeting minutes',
    'rispat.noMinutesDesc': 'No completed bookings on this date',
    'rispat.completed': 'Completed',
    'rispat.modalTitle': 'Meeting Minutes',
    
    // Meeting Rooms Page
    'meetingRooms.searchPlaceholder': 'Search rooms, locations, or facilities...',
    'meetingRooms.allCapacities': 'All Capacities',
    'meetingRooms.allStatus': 'All Status',
    'meetingRooms.available': 'Available',
    'meetingRooms.maintenance': 'Maintenance',
    'meetingRooms.reset': 'Reset',
    'meetingRooms.showingResults': 'Showing {filtered} of {total} rooms',
    'meetingRooms.noSearchResults': 'No rooms match the search criteria',
    'meetingRooms.roomsUsed': 'Rooms Used',
    'meetingRooms.capacity2': '2+ People',
    'meetingRooms.capacity4': '4+ People',
    'meetingRooms.capacity6': '6+ People',
    'meetingRooms.capacity8': '8+ People',
    'meetingRooms.capacity10': '10+ People',
    'meetingRooms.capacity15': '15+ People',
    'meetingRooms.capacity20': '20+ People',
    
    // Room Detail Page
    'roomDetail.roomInfo': 'Room Information',
    'roomDetail.capacity': 'Capacity',
    'roomDetail.floor': 'Floor',
    'roomDetail.address': 'Address',
    'roomDetail.facilities': 'Facilities',
    'roomDetail.status': 'Status',
    'roomDetail.available': 'Available',
    'roomDetail.ongoing': 'Ongoing',
    'roomDetail.upcoming': 'Upcoming',
    'roomDetail.maintenance': 'Maintenance',
    'roomDetail.bookingSchedule': 'Booking Schedule',
    'roomDetail.selectDate': 'Select Date',
    'roomDetail.quickOptions': 'Quick Options',
    'roomDetail.today': 'Today',
    'roomDetail.tomorrow': 'Tomorrow',
    'roomDetail.nextWeek': 'Next Week',
    'roomDetail.nextMonth': 'Next Month',
    'roomDetail.datesWithBookings': 'Dates with Bookings',
    'roomDetail.noBookings': 'No bookings for {date}',
    'roomDetail.roomAvailableAllDay': 'Room available all day',
    'roomDetail.bookRoom': 'Book Room',
    'roomDetail.unavailable': 'Unavailable',
    'roomDetail.availableTimeSlots': 'Available Time Slots - {date}',
    'roomDetail.past': 'PAST',
    'roomDetail.booked': 'Already Booked',
    'roomDetail.pastTime': 'Past Time',
    'roomDetail.tips': 'Tips:',
    'roomDetail.tip1': 'Click green slot to book the room at that time',
    'roomDetail.tip2': 'Red slot cannot be clicked because it\'s already booked',
    'roomDetail.tip3': 'Hover over red slot to see existing booking details',
    'roomDetail.tip4': 'Grey slot indicates past time',
    'roomDetail.edit': 'Edit',
    'roomDetail.activate': 'Activate',
    'roomDetail.deactivate': 'Deactivate',
    'roomDetail.delete': 'Delete',
    'roomDetail.cancel': 'Cancel',
    'roomDetail.processing': 'Processing...',
    'roomDetail.cannotDeactivate': 'Cannot Deactivate',
    'roomDetail.confirmActivate': 'Yes, Activate',
    'roomDetail.confirmDeactivate': 'Yes, Deactivate',
    'roomDetail.people': 'people',
    'roomDetail.bookingScheduleTitle': 'Booking Schedule - {date}',
    'roomDetail.totalBookings': 'Total {count} bookings for today',
    'roomDetail.booked': 'BOOKED',
    'roomDetail.date': 'Date',
    'roomDetail.time': 'Time',
    'roomDetail.pic': 'PIC',
    'roomDetail.participants': 'Participants',
    'roomDetail.type': 'Type',
    'roomDetail.facilities': 'Facilities',
    'roomDetail.duration': 'Duration',
    'roomDetail.hours': 'hours',
    'roomDetail.minutes': 'minutes',
    'roomDetail.slot': 'Slot',
    'roomDetail.scrollHint': '← Scroll to see other bookings →',
    'roomDetail.availableTimeSlots': 'Available Time Slots - {date}',
    'roomDetail.notAvailable': 'Not available',
    'roomDetail.past': 'PAST',
    'roomDetail.available': 'Available',
    'roomDetail.booked': 'Already Booked',
    'roomDetail.pastTime': 'Past Time',
    'roomDetail.tips': 'Tips:',
    'roomDetail.tip1': 'Click green slot to book the room at that time',
    'roomDetail.tip2': 'Red slot cannot be clicked because it\'s already booked',
    'roomDetail.tip3': 'Hover over red slot to see existing booking details',
    'roomDetail.tip4': 'Grey slot indicates past time',
    'roomDetail.tip5': 'Use date navigation to see bookings on other days',
    'roomDetail.confirmBooking': 'Booking Confirmation',
    'roomDetail.bookingConfirmation': 'You will book the room for the selected time',
    'roomDetail.room': 'Room',
    'roomDetail.date': 'Date',
    'roomDetail.time': 'Time',
    'roomDetail.noFacilities': 'None',
    'roomDetail.meeting': 'Meeting',
    'roomDetail.internal': 'internal',
    
    // Cancel Requests Page
    'cancelRequests.title': 'Cancellation Requests',
    'cancelRequests.subtitle': 'Manage all reservation cancellation requests',
    'cancelRequests.loading': 'Loading cancellation requests...',
    'cancelRequests.all': 'All',
    'cancelRequests.pending': 'Pending',
    'cancelRequests.approved': 'Approved',
    'cancelRequests.rejected': 'Rejected',
    'cancelRequests.noRequests': 'No Requests',
    'cancelRequests.noRequestsDesc': 'No reservation cancellation requests yet.',
    'cancelRequests.noRequestsFilter': 'No requests with status "{status}".',
    'cancelRequests.requestId': 'Cancellation Request #{id}',
    'cancelRequests.from': 'From',
    'cancelRequests.to': 'To',
    'cancelRequests.reservation': 'Reservation',
    'cancelRequests.aiBooking': 'AI Booking',
    'cancelRequests.formBooking': 'Form Booking',
    'cancelRequests.cancellationReason': 'Cancellation Reason',
    'cancelRequests.responseMessage': 'Response Message',
    'cancelRequests.replyMessage': 'Reply Message (Optional)',
    'cancelRequests.replyPlaceholder': 'Provide a reply message for the requester...',
    'cancelRequests.characters': 'characters',
    'cancelRequests.processing': 'Processing...',
    'cancelRequests.reject': 'Reject',
    'cancelRequests.approve': 'Approve',
    'cancelRequests.requestApproved': '✅ Your request has been approved',
    'cancelRequests.requestRejected': '❌ Your request has been rejected',
    'cancelRequests.message': 'Message',
    'cancelRequests.waitingResponse': 'Waiting Response',
    'cancelRequests.approved': 'Approved',
    'cancelRequests.rejected': 'Rejected',
    
    // Notification Bell
    'notification.title': 'Notifications',
    'notification.pendingRequests': '{count} cancellation requests waiting for response',
    'notification.noNewNotifications': 'No new notifications',
    'notification.noCancellationRequests': 'No cancellation requests',
    'notification.cancellationRequestFrom': 'Cancellation request from {requester}',
    'notification.viewAllRequests': 'View All Requests →',
    
    // Booking Form Page
    'bookingForm.title': 'Booking Form',
    'bookingForm.subtitle': 'Fill out the form to book a meeting room',
    'bookingForm.selectRoom': 'Select Room *',
    'bookingForm.loadingRooms': 'Loading rooms...',
    'bookingForm.selectRoomPlaceholder': 'Select meeting room',
    'bookingForm.people': 'people',
    'bookingForm.inactive': '- ❌ Inactive',
    'bookingForm.topic': 'Topic / Meeting Name *',
    'bookingForm.topicPlaceholder': 'Enter topic or meeting name',
    'bookingForm.pic': 'PIC (Person in Charge) *',
    'bookingForm.picPlaceholder': 'Enter PIC name',
    'bookingForm.participants': 'Number of Participants *',
    'bookingForm.participantsPlaceholder': 'Number of participants',
    'bookingForm.meetingDate': 'Meeting Date *',
    'bookingForm.meetingTime': 'Meeting Time *',
    'bookingForm.startTime': 'Start:',
    'bookingForm.endTime': 'End:',
    'bookingForm.duration': 'Duration:',
    'bookingForm.invalidTime': 'Invalid time',
    'bookingForm.hours': 'hours',
    'bookingForm.minutes': 'minutes',
    'bookingForm.meetingType': 'Meeting Type *',
    'bookingForm.internal': 'Internal',
    'bookingForm.external': 'External',
    'bookingForm.rispat': 'Meeting Minutes *',
    'bookingForm.no': 'No',
    'bookingForm.yes': 'Yes',
    'bookingForm.rispatHint': 'If you choose "Yes", you must upload meeting minutes after booking to complete the booking',
    'bookingForm.facilities': 'Facilities',
    'bookingForm.selectFacilities': 'Select available facilities in {roomName}',
    'bookingForm.selectRoomFirst': 'Select a room first to see available facilities',
    'bookingForm.selectedFacilities': 'Selected Facilities ({count}):',
    'bookingForm.cancel': 'Cancel',
    'bookingForm.processing': 'Processing...',
    'bookingForm.confirmBooking': 'Confirm Booking',
    'bookingForm.roomDetails': 'Room Details',
    'bookingForm.capacity': 'Capacity',
    'bookingForm.floor': 'Floor',
    'bookingForm.address': 'Address',
    'bookingForm.availableFacilities': 'Available Facilities',
    
    // Reservation Detail Page
    'reservationDetail.title': 'Reservation Details',
    'reservationDetail.subtitle': 'Complete meeting room reservation information',
    'reservationDetail.meeting': 'Meeting',
    'reservationDetail.date': 'Date',
    'reservationDetail.startTime': 'Start Time',
    'reservationDetail.endTime': 'End Time',
    'reservationDetail.pic': 'PIC',
    'reservationDetail.participants': 'Participants',
    'reservationDetail.people': 'people',
    'reservationDetail.meetingType': 'Meeting Type',
    'reservationDetail.facilities': 'Facilities',
    'reservationDetail.noSpecialFacilities': 'No special facilities',
    'reservationDetail.meetingMinutes': 'Meeting Minutes',
    'reservationDetail.noMinutesFile': 'No meeting minutes file yet',
    'reservationDetail.filesAvailable': '{count} files available',
    'reservationDetail.meetingOngoing': 'Meeting is ongoing - Upload available',
    'reservationDetail.meetingNotStarted': 'Meeting not started - Upload not available',
    'reservationDetail.meetingFinished': 'Meeting finished - Upload not available',
    'reservationDetail.upload': 'Upload',
    'reservationDetail.view': 'View',
    'reservationDetail.uploadMinutes': 'Upload meeting minutes',
    'reservationDetail.uploadOnlyDuringMeeting': 'Upload can only be done during ongoing meetings',
    'reservationDetail.summary': 'Summary',
    'reservationDetail.summarySubtitle': 'Brief reservation information',
    'reservationDetail.meetingRoom': 'Meeting Room',
    'reservationDetail.until': 'Until',
    'reservationDetail.meetingSchedule': 'Meeting Schedule',
    'reservationDetail.participantCount': 'Number of Participants',
    'reservationDetail.meetingInvitation': 'Meeting Invitation',
    'reservationDetail.backToReservations': 'Back to Reservations',
    'reservationDetail.uploadOnlyDuringMeetingAlert': 'Meeting minutes upload can only be done during ongoing meetings.',
    'reservationDetail.currentStatus': 'Current status: {status}',
    'reservationDetail.notStarted': 'Not started',
    'reservationDetail.finished': 'Finished',
    'reservationDetail.unknown': 'Unknown',
    
    // Profile Page
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account information and settings',
    'profile.active': 'Active',
    'profile.reservations': 'Reservations',
    'profile.completed': 'Completed',
    'profile.pending': 'Pending',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.role': 'Role',
    'profile.accountStatus': 'Account Status',
    'profile.recentActivity': 'Recent Activity',
    'profile.loadingActivities': 'Loading activities...',
    'profile.noRecentActivity': 'No recent activity',
    'profile.startWithReservation': 'Start by creating a room reservation',
    'profile.settings': 'Settings',
    'profile.settingsDesc': 'Manage application settings and preferences',
    'profile.helpCenter': 'Help Center',
    'profile.helpCenterDesc': 'Get help and technical support',
    'profile.roomReservation': 'Room Reservation',
    'profile.updateProfile': 'Update Profile',
    'profile.profileUpdated': 'Profile successfully updated',
    'profile.today': 'Today',
    'profile.yesterday': 'Yesterday',
    'profile.daysAgo': '{days} days ago',
    'profile.weeksAgo': '{weeks} weeks ago',
    'profile.weekAgo': '1 week ago',
    
    // Help Center Page
    'helpCenter.title': 'Help Center',
    'helpCenter.subtitle': 'Find answers to frequently asked questions',
    'helpCenter.faq': 'Frequently Asked Questions',
    'helpCenter.quickActions': 'Quick Actions',
    'helpCenter.contactUs': 'Contact Us',
    'helpCenter.aiAssistant': 'AI Assistant',
    'helpCenter.aiAssistantDesc': 'Get instant help with our AI Assistant available 24/7',
    'helpCenter.chatWithAI': 'Chat with AI',
    'helpCenter.viewMeetingRooms': 'View Meeting Rooms',
    'helpCenter.viewMyBookings': 'View My Bookings',
    'helpCenter.phone': 'Phone',
    'helpCenter.email': 'Email',
    'helpCenter.operatingHours': 'Operating hours: Monday - Friday, 08:00 - 17:00 WIB',
    'helpCenter.faq1Question': 'How to book a meeting room?',
    'helpCenter.faq1Answer': 'Select \'Meeting Rooms\' menu, choose an available room, then click \'Book Now\' and fill out the booking form.',
    'helpCenter.faq2Question': 'Can I cancel a booking?',
    'helpCenter.faq2Answer': 'Yes, you can cancel a booking through the \'Reservations\' menu and click the \'Cancel\' button on the booking you want to cancel.',
    'helpCenter.faq3Question': 'What is the maximum booking duration?',
    'helpCenter.faq3Answer': 'The maximum booking duration is 8 hours per day for each room.',
    'helpCenter.faq4Question': 'Is there a fee for booking rooms?',
    'helpCenter.faq4Answer': 'Meeting room booking is free for company employees.',
    'helpCenter.faq5Question': 'What if the desired room is already booked?',
    'helpCenter.faq5Answer': 'You can view the booking schedule on the \'Meeting Rooms\' page and choose an available time.',
    
    // Navigation
    'nav.logout': 'Logout',
    
    // Settings Page
    'settings.subtitle': 'Manage application settings and preferences',
    'settings.languageDesc': 'Choose your preferred language',
    'settings.changePasswordDesc': 'Change your password',
    'settings.twoFactorAuthDesc': 'Enhance account security',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.accountManagement': 'Account Management',
    'settings.exportData': 'Export Data',
    'settings.exportDataDesc': 'Download your data',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDesc': 'Permanently delete account',
    'settings.settingsSaved': 'Settings saved successfully!',
    'settings.saveError': 'Failed to save settings. Please try again.',
    'settings.saving': 'Saving...',
    'settings.unsavedChanges': 'You have unsaved changes',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.enterCurrentPassword': 'Enter current password',
    'settings.enterNewPassword': 'Enter new password',
    'settings.confirmNewPassword': 'Confirm new password',
    'settings.passwordRequired': 'All password fields are required',
    'settings.passwordMismatch': 'New password and confirmation do not match',
    'settings.passwordTooShort': 'Password must be at least 6 characters',
    'settings.passwordChanged': 'Password changed successfully! You will be redirected to the login page.',
    'settings.passwordChangeError': 'Failed to change password. Please try again.',
    'settings.cancel': 'Cancel',
    'settings.deleteWarning': 'Warning!',
    'settings.deleteWarningDesc': 'This action cannot be undone. All your data will be permanently deleted.',
    'settings.typeDeleteToConfirm': 'Type "delete" to confirm',
    'settings.deleteConfirmationRequired': 'You must type "delete" to confirm',
    'settings.accountDeleted': 'Account deleted successfully. You will be redirected to the login page.',
    'settings.deleteAccountError': 'Failed to delete account. Please try again.',
    'settings.deleting': 'Deleting...',
    
    // AI Assistant
    'ai.greeting': 'Hello! 👋 I am Spacio AI assistant ready to help you book meeting rooms easily! 🎯',
    'ai.bookRoom': 'Book Room',
    'ai.help': 'Help',
    'ai.clickMessage': 'Hello! I am Spacio AI Meeting Room Application',
    'ai.chatButton': 'Let\'s Chat with AI!',
    
    // Booking
    'booking.title': 'Room Booking',
    'booking.confirm': 'Confirm Booking',
    'booking.cancel': 'Cancel Booking',
    'booking.success': 'Booking successful!',
    
    // Profile
    'profile.title': 'Profile',
    'profile.settings': 'Settings',
    'profile.settingsDesc': 'Change account preferences',
    'profile.helpCenter': 'Help Center',
    'profile.helpCenterDesc': 'Get help and support',
    
    // Meeting Rooms
    'meetingRooms.title': 'Meeting Rooms',
    'meetingRooms.subtitle': 'Discover and book the perfect meeting space for your needs',
    'meetingRooms.addRoom': 'Add Room',
    'meetingRooms.totalRooms': 'Total Rooms',
    'meetingRooms.availableRooms': 'Available Rooms',
    'meetingRooms.totalCapacity': 'Total Capacity',
    'meetingRooms.loading': 'Loading room data...',
    'meetingRooms.error': 'Failed to Load Data',
    'meetingRooms.retry': 'Try Again',
    'meetingRooms.noRooms': 'No Rooms Available',
    'meetingRooms.noRoomsDesc': 'No meeting rooms are available yet. Add the first room to get started.',
    'meetingRooms.addFirstRoom': '➕ Add First Room',
    'meetingRooms.available': 'Available',
    'meetingRooms.ongoing': 'Ongoing',
    'meetingRooms.upcoming': 'Upcoming',
    'meetingRooms.occupied': 'Occupied',
    'meetingRooms.full': 'Full',
    'meetingRooms.left': 'Left',
    'meetingRooms.capacity': 'Capacity',
    'meetingRooms.address': 'Address',
    'meetingRooms.facilities': 'Facilities',
    'meetingRooms.book': 'Book',
    'meetingRooms.people': 'people',
    
    // Reservations
    'reservations.title': 'My Reservations',
    'reservations.subtitle': 'Manage and monitor all your meeting room reservations',
    'reservations.totalReservations': 'Total Reservations',
    'reservations.activeReservations': 'Active Reservations',
    'reservations.roomsUsed': 'Rooms Used',
    'reservations.searchPlaceholder': 'Search by topic or room...',
    'reservations.sortNewest': 'Newest',
    'reservations.sortOldest': 'Oldest',
    'reservations.noReservations': 'No Reservations',
    'reservations.noReservationsDesc': 'You haven\'t made any bookings yet. Start by finding available rooms and make your first reservation.',
    'reservations.searchRooms': '🔍 Search Rooms',
    'reservations.active': 'Active',
    'reservations.date': 'Date',
    'reservations.time': 'Time',
    'reservations.pic': 'PIC',
    'reservations.participants': 'Participants',
    'reservations.detail': 'Detail',
    'reservations.complete': 'Complete',
    'reservations.cancel': 'Cancel',
    'reservations.confirmCancel': 'Are you sure you want to cancel this booking? Data will be deleted from the database.',
    'reservations.cancelSuccess': 'Booking successfully cancelled and deleted from database!',
    'reservations.cancelError': 'Failed to cancel booking. Please try again.',
    'reservations.completeError': 'Failed to complete booking. Please try again.',
    
    // Footer
    'footer.aboutUs': 'About Us',
    'footer.ourProfile': 'Our Profile',
    'footer.contactUs': 'Contact Us',
    'footer.investorRelations': 'Investor Relations',
    'footer.annualReport': 'Annual Report',
    'footer.publications': 'Publications',
    'footer.news': 'News',
    'footer.airportInfo': 'Airport Information & Profile',
    'footer.memberOf': 'Member Of',
    'footer.airportsCenter': 'InJourney Airports Center',
    'footer.airportName': 'Soekarno-Hatta International Airport',
    'footer.address': 'Jl. M2, Pajang, Kec. Benda, Kota Tangerang, Banten 15126',
    'footer.companyName': 'PT Angkasa Pura Indonesia',
    'footer.copyright': 'PT Angkasa Pura Indonesia © 2024. All Rights Reserved',
  },
  ja: {
    // Navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.meetingRooms': '会議室',
    'nav.aiAssistant': 'AIアシスタント',
    'nav.reservations': '予約',
    'nav.history': '履歴',
    'nav.profile': 'プロフィール',
    'nav.settings': '設定',
    'nav.helpCenter': 'ヘルプセンター',
    
    // Settings
    'settings.title': '設定',
    'settings.appearance': '外観',
    'settings.darkMode': 'ダークモード',
    'settings.darkModeDesc': 'ダークテーマを有効にする',
    'settings.language': '言語',
    'settings.privacySecurity': 'プライバシーとセキュリティ',
    'settings.changePassword': 'パスワード変更',
    'settings.twoFactorAuth': '2FA認証',
    'settings.saveSettings': '設定を保存',
    
    // Language options
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English',
    'language.japanese': '日本語',
    
    // Common
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.loading': '読み込み中...',
    'common.error': 'エラーが発生しました',
    'common.success': '成功',
    
    // Dashboard
    'dashboard.title': 'ダッシュボード',
    'dashboard.welcome': 'ようこそ',
    'dashboard.upcomingMeetings': '今後の会議',
    'dashboard.quickActions': 'クイックアクション',
    'dashboard.heroTitle': 'AIに完璧な会議室の予約を手伝ってもらいましょう！',
    'dashboard.heroSubtitle': 'スマートなAIアシスタントの助けを借りて、理想的な会議室を瞬時に見つけて予約しましょう。予約プロセスがより速く、効率的で、あなたのニーズに合わせてカスタマイズされます。',
    'dashboard.upcomingReservations': '今後の予約',
    'dashboard.bookingHistory': '予約履歴',
    'dashboard.featuredFeatures': '注目の機能',
    'dashboard.smartRecommendations': 'スマート推奨',
    'dashboard.smartRecommendationsDesc': '私たちのAIは、あなたのニーズ、参加者数、設備の好みに基づいて最適な部屋を推奨します。',
    'dashboard.automaticScheduling': '自動スケジューリング',
    'dashboard.automaticSchedulingDesc': 'スケジュールの競合なしに、すべての会議参加者に適した最適な時間スロットを自動的に見つけます。',
    'dashboard.naturalLanguage': '自然言語',
    'dashboard.naturalLanguageDesc': 'より直感的な予約体験のために、人間の言語を使用してAIアシスタントとやり取りします。',
    'dashboard.noReservations': 'まだ予約がありません。',
    'dashboard.noReservationsDesc': 'AIアシスタントまたは手動フォームを通じて予約を作成してみてください。',
    'dashboard.viewAllReservations': 'すべての予約を表示',
    'dashboard.viewHistory': '履歴を表示',
    'dashboard.viewRispat': 'Rispatを表示',
    'dashboard.historyDesc': '最新の履歴の概要（データベースデータが削除されてもローカルに保存されます）。',
    
    // Cancel Requests
    'dashboard.cancelRequests': 'キャンセルリクエスト',
    'dashboard.cancelRequestsDesc': 'すべての予約キャンセルリクエストを管理',
    'dashboard.manageRequests': 'リクエストを管理',
    'dashboard.cancelRequestsInstruction': '上記のボタンをクリックして、すべてのキャンセルリクエストを表示・管理',
    
    // History Page
    'history.title': '予約履歴',
    'history.subtitle': '会議室予約の履歴',
    'history.selectDate': '日付を選択',
    'history.bookingStatus': '予約ステータス',
    'history.statusDescription': '選択した日付の予約（キャンセル済み・完了済み）を表示',
    'history.noHistory': '履歴なし',
    'history.noHistoryDesc': '選択した日付に予約がありません',
    'history.cancelReason': 'キャンセル理由',
    'history.expired': '期限切れ',
    
    // Rispat Page
    'rispat.title': 'Rispatを表示',
    'rispat.subtitle': '完了した会議議事録を表示・管理',
    'rispat.selectDate': '日付を選択',
    'rispat.meetingMinutes': '会議議事録',
    'rispat.description': '完了した予約を表示して会議議事録を確認',
    'rispat.noMinutes': '議事録なし',
    'rispat.noMinutesDesc': 'この日付に完了した予約がありません',
    'rispat.completed': '完了',
    'rispat.modalTitle': '会議議事録',
    
    // Meeting Rooms Page
    'meetingRooms.searchPlaceholder': '部屋、場所、設備を検索...',
    'meetingRooms.allCapacities': 'すべての収容人数',
    'meetingRooms.allStatus': 'すべてのステータス',
    'meetingRooms.available': '利用可能',
    'meetingRooms.maintenance': 'メンテナンス',
    'meetingRooms.reset': 'リセット',
    'meetingRooms.showingResults': '{filtered}件中{total}件の部屋を表示',
    'meetingRooms.noSearchResults': '検索条件に一致する部屋がありません',
    'meetingRooms.roomsUsed': '使用中',
    'meetingRooms.capacity2': '2人以上',
    'meetingRooms.capacity4': '4人以上',
    'meetingRooms.capacity6': '6人以上',
    'meetingRooms.capacity8': '8人以上',
    'meetingRooms.capacity10': '10人以上',
    'meetingRooms.capacity15': '15人以上',
    'meetingRooms.capacity20': '20人以上',
    
    // Room Detail Page
    'roomDetail.roomInfo': '部屋情報',
    'roomDetail.capacity': '収容人数',
    'roomDetail.floor': '階',
    'roomDetail.address': '住所',
    'roomDetail.facilities': '設備',
    'roomDetail.status': 'ステータス',
    'roomDetail.available': '利用可能',
    'roomDetail.ongoing': '進行中',
    'roomDetail.upcoming': '予定',
    'roomDetail.maintenance': 'メンテナンス',
    'roomDetail.bookingSchedule': '予約スケジュール',
    'roomDetail.selectDate': '日付を選択',
    'roomDetail.quickOptions': 'クイックオプション',
    'roomDetail.today': '今日',
    'roomDetail.tomorrow': '明日',
    'roomDetail.nextWeek': '来週',
    'roomDetail.nextMonth': '来月',
    'roomDetail.datesWithBookings': '予約がある日付',
    'roomDetail.noBookings': '{date}の予約はありません',
    'roomDetail.roomAvailableAllDay': '部屋は一日中利用可能です',
    'roomDetail.bookRoom': '部屋を予約',
    'roomDetail.unavailable': '利用不可',
    'roomDetail.availableTimeSlots': '利用可能な時間帯 - {date}',
    'roomDetail.past': '過去',
    'roomDetail.booked': '予約済み',
    'roomDetail.pastTime': '過去の時間',
    'roomDetail.tips': 'ヒント：',
    'roomDetail.tip1': '緑のスロットをクリックしてその時間に部屋を予約',
    'roomDetail.tip2': '赤のスロットは既に予約されているためクリックできません',
    'roomDetail.tip3': '赤のスロットにホバーして既存の予約詳細を表示',
    'roomDetail.tip4': 'グレーのスロットは過去の時間を示します',
    'roomDetail.edit': '編集',
    'roomDetail.activate': '有効化',
    'roomDetail.deactivate': '無効化',
    'roomDetail.delete': '削除',
    'roomDetail.cancel': 'キャンセル',
    'roomDetail.processing': '処理中...',
    'roomDetail.cannotDeactivate': '無効化できません',
    'roomDetail.confirmActivate': 'はい、有効化します',
    'roomDetail.confirmDeactivate': 'はい、無効化します',
    'roomDetail.people': '人',
    'roomDetail.bookingScheduleTitle': '予約スケジュール - {date}',
    'roomDetail.totalBookings': '今日の予約合計 {count} 件',
    'roomDetail.booked': '予約済み',
    'roomDetail.date': '日付',
    'roomDetail.time': '時間',
    'roomDetail.pic': 'PIC',
    'roomDetail.participants': '参加者',
    'roomDetail.type': '種類',
    'roomDetail.facilities': '設備',
    'roomDetail.duration': '時間',
    'roomDetail.hours': '時間',
    'roomDetail.minutes': '分',
    'roomDetail.slot': 'スロット',
    'roomDetail.scrollHint': '← 他の予約を見るにはスクロール →',
    'roomDetail.availableTimeSlots': '利用可能な時間帯 - {date}',
    'roomDetail.notAvailable': '利用不可',
    'roomDetail.past': '過去',
    'roomDetail.available': '利用可能',
    'roomDetail.booked': '予約済み',
    'roomDetail.pastTime': '過去の時間',
    'roomDetail.tips': 'ヒント：',
    'roomDetail.tip1': '緑のスロットをクリックしてその時間に部屋を予約',
    'roomDetail.tip2': '赤のスロットは既に予約されているためクリックできません',
    'roomDetail.tip3': '赤のスロットにホバーして既存の予約詳細を表示',
    'roomDetail.tip4': 'グレーのスロットは過去の時間を示します',
    'roomDetail.tip5': '日付ナビゲーションを使用して他の日の予約を表示',
    'roomDetail.confirmBooking': '予約確認',
    'roomDetail.bookingConfirmation': '選択した時間に部屋を予約します',
    'roomDetail.room': '部屋',
    'roomDetail.date': '日付',
    'roomDetail.time': '時間',
    'roomDetail.noFacilities': 'なし',
    'roomDetail.meeting': '会議',
    'roomDetail.internal': '内部',
    
    // Cancel Requests Page
    'cancelRequests.title': 'キャンセルリクエスト',
    'cancelRequests.subtitle': 'すべての予約キャンセルリクエストを管理',
    'cancelRequests.loading': 'キャンセルリクエストを読み込み中...',
    'cancelRequests.all': 'すべて',
    'cancelRequests.pending': '保留中',
    'cancelRequests.approved': '承認済み',
    'cancelRequests.rejected': '拒否済み',
    'cancelRequests.noRequests': 'リクエストなし',
    'cancelRequests.noRequestsDesc': 'まだ予約キャンセルリクエストがありません。',
    'cancelRequests.noRequestsFilter': 'ステータス「{status}」のリクエストがありません。',
    'cancelRequests.requestId': 'キャンセルリクエスト #{id}',
    'cancelRequests.from': '送信者',
    'cancelRequests.to': '宛先',
    'cancelRequests.reservation': '予約',
    'cancelRequests.aiBooking': 'AI予約',
    'cancelRequests.formBooking': 'フォーム予約',
    'cancelRequests.cancellationReason': 'キャンセル理由',
    'cancelRequests.responseMessage': '返信メッセージ',
    'cancelRequests.replyMessage': '返信メッセージ（オプション）',
    'cancelRequests.replyPlaceholder': 'リクエスターへの返信メッセージを入力...',
    'cancelRequests.characters': '文字',
    'cancelRequests.processing': '処理中...',
    'cancelRequests.reject': '拒否',
    'cancelRequests.approve': '承認',
    'cancelRequests.requestApproved': '✅ あなたのリクエストが承認されました',
    'cancelRequests.requestRejected': '❌ あなたのリクエストが拒否されました',
    'cancelRequests.message': 'メッセージ',
    'cancelRequests.waitingResponse': '返信待ち',
    'cancelRequests.approved': '承認済み',
    'cancelRequests.rejected': '拒否済み',
    
    // Notification Bell
    'notification.title': '通知',
    'notification.pendingRequests': '{count}件のキャンセルリクエストが返信待ちです',
    'notification.noNewNotifications': '新しい通知はありません',
    'notification.noCancellationRequests': 'キャンセルリクエストはありません',
    'notification.cancellationRequestFrom': '{requester}からのキャンセルリクエスト',
    'notification.viewAllRequests': 'すべてのリクエストを表示 →',
    
    // Booking Form Page
    'bookingForm.title': '予約フォーム',
    'bookingForm.subtitle': '会議室を予約するためのフォームに記入してください',
    'bookingForm.selectRoom': '部屋を選択 *',
    'bookingForm.loadingRooms': '部屋を読み込み中...',
    'bookingForm.selectRoomPlaceholder': '会議室を選択',
    'bookingForm.people': '人',
    'bookingForm.inactive': '- ❌ 無効',
    'bookingForm.topic': 'トピック / 会議名 *',
    'bookingForm.topicPlaceholder': 'トピックまたは会議名を入力',
    'bookingForm.pic': 'PIC（責任者）*',
    'bookingForm.picPlaceholder': 'PIC名を入力',
    'bookingForm.participants': '参加者数 *',
    'bookingForm.participantsPlaceholder': '参加者数',
    'bookingForm.meetingDate': '会議日 *',
    'bookingForm.meetingTime': '会議時間 *',
    'bookingForm.startTime': '開始:',
    'bookingForm.endTime': '終了:',
    'bookingForm.duration': '時間:',
    'bookingForm.invalidTime': '無効な時間',
    'bookingForm.hours': '時間',
    'bookingForm.minutes': '分',
    'bookingForm.meetingType': '会議タイプ *',
    'bookingForm.internal': '内部',
    'bookingForm.external': '外部',
    'bookingForm.rispat': '議事録 *',
    'bookingForm.no': 'いいえ',
    'bookingForm.yes': 'はい',
    'bookingForm.rispatHint': '「はい」を選択した場合、予約後に議事録をアップロードして予約を完了する必要があります',
    'bookingForm.facilities': '設備',
    'bookingForm.selectFacilities': '{roomName}で利用可能な設備を選択',
    'bookingForm.selectRoomFirst': '利用可能な設備を表示するには、まず部屋を選択してください',
    'bookingForm.selectedFacilities': '選択された設備 ({count}):',
    'bookingForm.cancel': 'キャンセル',
    'bookingForm.processing': '処理中...',
    'bookingForm.confirmBooking': '予約確認',
    'bookingForm.roomDetails': '部屋詳細',
    'bookingForm.capacity': '収容人数',
    'bookingForm.floor': '階',
    'bookingForm.address': '住所',
    'bookingForm.availableFacilities': '利用可能な設備',
    
    // Reservation Detail Page
    'reservationDetail.title': '予約詳細',
    'reservationDetail.subtitle': '会議室予約の完全な情報',
    'reservationDetail.meeting': '会議',
    'reservationDetail.date': '日付',
    'reservationDetail.startTime': '開始時間',
    'reservationDetail.endTime': '終了時間',
    'reservationDetail.pic': 'PIC',
    'reservationDetail.participants': '参加者',
    'reservationDetail.people': '人',
    'reservationDetail.meetingType': '会議タイプ',
    'reservationDetail.facilities': '設備',
    'reservationDetail.noSpecialFacilities': '特別な設備はありません',
    'reservationDetail.meetingMinutes': '議事録',
    'reservationDetail.noMinutesFile': 'まだ議事録ファイルがありません',
    'reservationDetail.filesAvailable': '{count}ファイル利用可能',
    'reservationDetail.meetingOngoing': '会議進行中 - アップロード可能',
    'reservationDetail.meetingNotStarted': '会議未開始 - アップロード不可',
    'reservationDetail.meetingFinished': '会議終了 - アップロード不可',
    'reservationDetail.upload': 'アップロード',
    'reservationDetail.view': '表示',
    'reservationDetail.uploadMinutes': '議事録をアップロード',
    'reservationDetail.uploadOnlyDuringMeeting': 'アップロードは会議進行中のみ可能です',
    'reservationDetail.summary': '概要',
    'reservationDetail.summarySubtitle': '予約の簡潔な情報',
    'reservationDetail.meetingRoom': '会議室',
    'reservationDetail.until': 'まで',
    'reservationDetail.meetingSchedule': '会議スケジュール',
    'reservationDetail.participantCount': '参加者数',
    'reservationDetail.meetingInvitation': '会議招待',
    'reservationDetail.backToReservations': '予約に戻る',
    'reservationDetail.uploadOnlyDuringMeetingAlert': '議事録のアップロードは会議進行中のみ可能です。',
    'reservationDetail.currentStatus': '現在のステータス: {status}',
    'reservationDetail.notStarted': '未開始',
    'reservationDetail.finished': '終了済み',
    'reservationDetail.unknown': '不明',
    
    // Profile Page
    'profile.title': 'プロフィール',
    'profile.subtitle': 'アカウント情報と設定を管理',
    'profile.active': 'アクティブ',
    'profile.reservations': '予約',
    'profile.completed': '完了',
    'profile.pending': '保留中',
    'profile.personalInfo': '個人情報',
    'profile.fullName': 'フルネーム',
    'profile.email': 'メール',
    'profile.role': 'ロール',
    'profile.accountStatus': 'アカウントステータス',
    'profile.recentActivity': '最近のアクティビティ',
    'profile.loadingActivities': 'アクティビティを読み込み中...',
    'profile.noRecentActivity': '最近のアクティビティがありません',
    'profile.startWithReservation': '部屋の予約を作成することから始めましょう',
    'profile.settings': '設定',
    'profile.settingsDesc': 'アプリケーション設定と環境設定を管理',
    'profile.helpCenter': 'ヘルプセンター',
    'profile.helpCenterDesc': 'ヘルプとテクニカルサポートを取得',
    'profile.roomReservation': '部屋予約',
    'profile.updateProfile': 'プロフィール更新',
    'profile.profileUpdated': 'プロフィールが正常に更新されました',
    'profile.today': '今日',
    'profile.yesterday': '昨日',
    'profile.daysAgo': '{days}日前',
    'profile.weeksAgo': '{weeks}週間前',
    'profile.weekAgo': '1週間前',
    
    // Help Center Page
    'helpCenter.title': 'ヘルプセンター',
    'helpCenter.subtitle': 'よくある質問の回答を見つけましょう',
    'helpCenter.faq': 'よくある質問',
    'helpCenter.quickActions': 'クイックアクション',
    'helpCenter.contactUs': 'お問い合わせ',
    'helpCenter.aiAssistant': 'AIアシスタント',
    'helpCenter.aiAssistantDesc': '24時間365日利用可能なAIアシスタントで即座にサポートを受けられます',
    'helpCenter.chatWithAI': 'AIとチャット',
    'helpCenter.viewMeetingRooms': '会議室を見る',
    'helpCenter.viewMyBookings': '予約を確認',
    'helpCenter.phone': '電話',
    'helpCenter.email': 'メール',
    'helpCenter.operatingHours': '営業時間: 月曜日 - 金曜日, 08:00 - 17:00 WIB',
    'helpCenter.faq1Question': '会議室の予約方法は？',
    'helpCenter.faq1Answer': '\'会議室\'メニューを選択し、利用可能な部屋を選んで、\'今すぐ予約\'をクリックして予約フォームに記入してください。',
    'helpCenter.faq2Question': '予約をキャンセルできますか？',
    'helpCenter.faq2Answer': 'はい、\'予約\'メニューからキャンセルしたい予約の\'キャンセル\'ボタンをクリックしてキャンセルできます。',
    'helpCenter.faq3Question': '最大予約時間はどのくらいですか？',
    'helpCenter.faq3Answer': '各部屋の最大予約時間は1日8時間です。',
    'helpCenter.faq4Question': '部屋の予約に料金はかかりますか？',
    'helpCenter.faq4Answer': '会社の従業員にとって会議室の予約は無料です。',
    'helpCenter.faq5Question': '希望の部屋が既に予約されている場合はどうすればよいですか？',
    'helpCenter.faq5Answer': '\'会議室\'ページで予約スケジュールを確認し、利用可能な時間を選択できます。',
    
    // Navigation
    'nav.logout': 'ログアウト',
    
    // Settings Page
    'settings.subtitle': 'アプリケーション設定と環境設定を管理',
    'settings.languageDesc': '希望する言語を選択',
    'settings.changePasswordDesc': 'パスワードを変更',
    'settings.twoFactorAuthDesc': 'アカウントセキュリティを強化',
    'settings.notifications': '通知',
    'settings.emailNotifications': 'メール通知',
    'settings.pushNotifications': 'プッシュ通知',
    'settings.accountManagement': 'アカウント管理',
    'settings.exportData': 'データエクスポート',
    'settings.exportDataDesc': 'データをダウンロード',
    'settings.deleteAccount': 'アカウント削除',
    'settings.deleteAccountDesc': 'アカウントを永続的に削除',
    'settings.settingsSaved': '設定が正常に保存されました！',
    'settings.saveError': '設定の保存に失敗しました。もう一度お試しください。',
    'settings.saving': '保存中...',
    'settings.unsavedChanges': '保存されていない変更があります',
    'settings.currentPassword': '現在のパスワード',
    'settings.newPassword': '新しいパスワード',
    'settings.confirmPassword': 'パスワード確認',
    'settings.enterCurrentPassword': '現在のパスワードを入力',
    'settings.enterNewPassword': '新しいパスワードを入力',
    'settings.confirmNewPassword': '新しいパスワードを確認',
    'settings.passwordRequired': 'すべてのパスワードフィールドが必要です',
    'settings.passwordMismatch': '新しいパスワードと確認が一致しません',
    'settings.passwordTooShort': 'パスワードは最低6文字である必要があります',
    'settings.passwordChanged': 'パスワードが正常に変更されました！ログインページにリダイレクトされます。',
    'settings.passwordChangeError': 'パスワードの変更に失敗しました。もう一度お試しください。',
    'settings.cancel': 'キャンセル',
    'settings.deleteWarning': '警告！',
    'settings.deleteWarningDesc': 'この操作は元に戻せません。すべてのデータが永続的に削除されます。',
    'settings.typeDeleteToConfirm': '確認のため「delete」と入力してください',
    'settings.deleteConfirmationRequired': '確認のため「delete」と入力する必要があります',
    'settings.accountDeleted': 'アカウントが正常に削除されました。ログインページにリダイレクトされます。',
    'settings.deleteAccountError': 'アカウントの削除に失敗しました。もう一度お試しください。',
    'settings.deleting': '削除中...',
    
    // AI Assistant
    'ai.greeting': 'こんにちは！👋 私はSpacio AIアシスタントです。会議室の予約を簡単にお手伝いします！🎯',
    'ai.bookRoom': '部屋を予約',
    'ai.help': 'ヘルプ',
    'ai.clickMessage': 'こんにちは！私はSpacio AI会議室アプリケーションです',
    'ai.chatButton': 'AIとチャットしましょう！',
    
    // Booking
    'booking.title': '部屋予約',
    'booking.confirm': '予約確認',
    'booking.cancel': '予約キャンセル',
    'booking.success': '予約が成功しました！',
    
    // Profile
    'profile.title': 'プロフィール',
    'profile.settings': '設定',
    'profile.settingsDesc': 'アカウント設定を変更',
    'profile.helpCenter': 'ヘルプセンター',
    'profile.helpCenterDesc': 'ヘルプとサポートを取得',
    
    // Meeting Rooms
    'meetingRooms.title': '会議室',
    'meetingRooms.subtitle': 'ニーズに合った完璧な会議スペースを見つけて予約しましょう',
    'meetingRooms.addRoom': '部屋を追加',
    'meetingRooms.totalRooms': '総部屋数',
    'meetingRooms.availableRooms': '利用可能な部屋',
    'meetingRooms.totalCapacity': '総収容人数',
    'meetingRooms.loading': '部屋データを読み込み中...',
    'meetingRooms.error': 'データの読み込みに失敗',
    'meetingRooms.retry': '再試行',
    'meetingRooms.noRooms': '部屋がありません',
    'meetingRooms.noRoomsDesc': 'まだ会議室がありません。最初の部屋を追加して始めましょう。',
    'meetingRooms.addFirstRoom': '➕ 最初の部屋を追加',
    'meetingRooms.available': '利用可能',
    'meetingRooms.ongoing': '進行中',
    'meetingRooms.upcoming': '予定',
    'meetingRooms.occupied': '使用中',
    'meetingRooms.full': '満室',
    'meetingRooms.left': '残り',
    'meetingRooms.capacity': '収容人数',
    'meetingRooms.address': '住所',
    'meetingRooms.facilities': '設備',
    'meetingRooms.book': '予約',
    'meetingRooms.people': '人',
    
    // Reservations
    'reservations.title': '私の予約',
    'reservations.subtitle': '会議室の予約を管理・監視しましょう',
    'reservations.totalReservations': '総予約数',
    'reservations.activeReservations': 'アクティブな予約',
    'reservations.roomsUsed': '使用された部屋',
    'reservations.searchPlaceholder': 'トピックまたは部屋で検索...',
    'reservations.sortNewest': '最新',
    'reservations.sortOldest': '最古',
    'reservations.noReservations': '予約がありません',
    'reservations.noReservationsDesc': 'まだ予約を作成していません。利用可能な部屋を見つけて最初の予約を作成しましょう。',
    'reservations.searchRooms': '🔍 部屋を検索',
    'reservations.active': 'アクティブ',
    'reservations.date': '日付',
    'reservations.time': '時間',
    'reservations.pic': 'PIC',
    'reservations.participants': '参加者',
    'reservations.detail': '詳細',
    'reservations.complete': '完了',
    'reservations.cancel': 'キャンセル',
    'reservations.confirmCancel': 'この予約をキャンセルしてもよろしいですか？データはデータベースから削除されます。',
    'reservations.cancelSuccess': '予約が正常にキャンセルされ、データベースから削除されました！',
    'reservations.cancelError': '予約のキャンセルに失敗しました。もう一度お試しください。',
    'reservations.completeError': '予約の完了に失敗しました。もう一度お試しください。',
    
    // Footer
    'footer.aboutUs': '私たちについて',
    'footer.ourProfile': '私たちのプロフィール',
    'footer.contactUs': 'お問い合わせ',
    'footer.investorRelations': '投資家関係',
    'footer.annualReport': '年次報告書',
    'footer.publications': '出版物',
    'footer.news': 'ニュース',
    'footer.airportInfo': '空港情報とプロフィール',
    'footer.memberOf': 'メンバー',
    'footer.airportsCenter': 'InJourney エアポートセンター',
    'footer.airportName': 'スカルノ・ハッタ国際空港',
    'footer.address': 'Jl. M2, Pajang, Kec. Benda, Kota Tangerang, Banten 15126',
    'footer.companyName': 'PT Angkasa Pura Indonesia',
    'footer.copyright': 'PT Angkasa Pura Indonesia © 2024. All Rights Reserved',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('id');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('app_language') as Language;
    if (savedLanguage && ['id', 'en', 'ja'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
